Account for M1 arm64 within api tests. ${PWD} NOT $(pwd). [[ ]] NOT [ ].

diff --git a/t/api b/t/api
--- a/t/api
+++ b/t/api
@@ -7,8 +7,8 @@ echo "S.H.I.E.L.D. API TESTS"
 echo "======================"
 echo
 
-PATH=$(pwd):$(pwd)/bin:${PATH}
-WORKDIR=$(pwd)/tmp/t
+PATH=${PWD}:${PWD}/bin:${PATH}
+WORKDIR=${PWD}/tmp/t
 DATA_DIRECTORY=${WORKDIR}/var/
 SHIELD_DAEMON_HOST=127.0.0.1
 SHIELD_DAEMON_PORT=8282
@@ -34,20 +34,32 @@ cleanup () {
 trap "cleanup >&2" EXIT QUIT INT TERM
 
 spin_vault() {
-  if [[ ! -f $(pwd)/bin/vault ]]; then
+  if [[ ! -f ${PWD}/bin/vault ]]; then
     VAULT_VERSION=0.9.0
     echo "... retrieving vault $VAULT_VERSION form the web..."
-    case $OSTYPE in
-    *darwin*) curl -C - -sLo ${WORKDIR}/vault.zip https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_darwin_amd64.zip ;;
-    *linux*)  curl -C - -sLo ${WORKDIR}/vault.zip https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip  ;;
-    *) echo >&2 "unable to determine OSTYPE, and the vault command was not found.  bailing..."; exit 1 ;;
+    case "${OSTYPE}" in
+      (*darwin*)
+        case "$(uname -m)" in
+          (x86_64)
+            curl -C - -sLo ${WORKDIR}/vault.zip https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_darwin_amd64.zip 
+            ;;
+          (arm64)
+            vault_0.9.0_darwin_amd64.zip 
+            ;;
+          (*)
+            echo >&2 "Architecture is neither x86_64 nor arm64, and the vault command was not found.  bailing..."; exit 1
+            ;;
+        esac
+        ;;
+      (*linux*)  curl -C - -sLo ${WORKDIR}/vault.zip https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip  ;;
+      (*) echo >&2 "unable to determine OSTYPE, and the vault command was not found.  bailing..."; exit 1 ;;
     esac
 
     pushd $WORKDIR
       rm -f vault
       unzip vault.zip
     popd
-    mv $WORKDIR/vault $(pwd)/bin/vault
+    mv $WORKDIR/vault ${PWD}/bin/vault
   fi
 
   cat >${WORKDIR}/etc/vault.conf <<EOF
@@ -62,8 +74,8 @@ EOF
   set -e
   echo ">> Setting up a local (loopback) Vault"
   export PATH=$PATH:$WORKDIR
-  $(pwd)/bin/vault version
-  $(pwd)/bin/vault server -config ${WORKDIR}/etc/vault.conf 2>&1 &
+  ${PWD}/bin/vault version
+  ${PWD}/bin/vault server -config ${WORKDIR}/etc/vault.conf 2>&1 &
   set +e
 }
 
@@ -78,7 +90,7 @@ debug:    true
 data-dir: ${DATA_DIRECTORY}
 web-root: ./web/htdocs
 plugin_paths:
-  - $(pwd)
+  - ${PWD}
 
 vault:
   address: http://127.0.0.1:8219
@@ -166,7 +178,7 @@ authorized_keys_file: ${WORKDIR}/var/authorized_keys
 host_key_file: ${WORKDIR}/var/shield-agent_key
 listen_address: ${SHIELD_AGENT_ADDR}
 plugin_paths:
-  - $(pwd)
+  - ${PWD}
 
 name: t-api-agent
 registration:
@@ -221,7 +233,7 @@ done_testing() {
 
 TESTS=""
 testing() {
-	[ -z "$TESTS" ] && return 0
+	[[ -z "$TESTS" ]] && return 0
 	grep -iq " -$1 "  <<<" $TESTS " && return 1
 	grep -iq  " $1 "  <<<" $TESTS " && return 0
 	grep -iq  " all " <<<" $TESTS " && return 0
